### ISSUE TITLE
Incorrect file size calculation

### ISSUE THREAD

**Issue by stephan-james** [KarimMokhtar/react-drag-drop-files#100]
File size in megabytes should be calculate via **1024 bytes x 1024 kilobytes**. Currently it's based on 1000 x 1000 which leads to incorrect behaviour.

**Comment by rjgotten** [comment]
> File size in megabytes should be calculate via **1024 bytes x 1024 kilobytes**. Currently it's based on 1000 x 1000 which leads to incorrect behaviour.

The 1024 binary magnitude should use the KiB (kibibyte) and MiB (Mebibyte) SI units.
The KB (kilobyte) and MB (Megabyte) SI units _should_ use 1000.

**Comment by KarimMokhtar** [comment]
solved in v. 2.3.11
Thanks for your contribution
