### ISSUE TITLE
how to reset the file uploader?

### ISSUE THREAD

**Issue by bhavya-agathsya** [KarimMokhtar/react-drag-drop-files#102]
Even after deselecting all the selected images the file uploader still showing file uploaded successfully text. It should show upload or drop a file like before. I tried fileOrFiles option but it didn't worked for me. So how can I make it work ??

**Comment by KarimMokhtar** [comment]
@bhavya-agathsya 
sending fileOrFiles={null} should solve the issue, make sure you are using v. 2.3.10 or above
