### ISSUE TITLE
[Feature request] Allow custom component when drag&dropping

### ISSUE THREAD

**Issue by nnavascues** [KarimMokhtar/react-drag-drop-files#103]
Hi!
I see in the documentation that the CSS of the component that renders when the drag&dropping state is enabled can be customized, but I believe it would be great if we could change the whole component (passing a React Component). 
Thanks!

**Comment by saikishoretv** [comment]
I am looking a solution for the same.

**Comment by KarimMokhtar** [comment]
@nnavascues you can pass a children to the component with your own styling and elements.
