### ISSUE TITLE
Demo is not working

### ISSUE THREAD

**Issue by felpsio** [KarimMokhtar/react-drag-drop-files#109]
When I access the demo link in the docs I get the following error:

![Screenshot 2023-03-02 at 11 49 19](https://user-images.githubusercontent.com/7477504/222462384-27273977-430c-4512-b985-004831bfb341.png)

**Comment by KarimMokhtar** [comment]
Maybe it was an issue with sandbox, please try again. 
![Screenshot 2024-10-22 at 23 34 37](https://github.com/user-attachments/assets/9c504dbf-44bc-484a-aba3-69d255405cfb)
