### ISSUE TITLE
Doesnt actually upload files or allow you trigger an action afterwards?

### ISSUE THREAD

**Issue by JJRobertsSex30** [KarimMokhtar/react-drag-drop-files#110]
Maybe I am being really dim here but files dragged or uploaded with this don't get uploaded anywhere. Nor is there a place to specify where they should get uploaded nor what action to take with such files (on the server side like processing / converting) when they do get uploaded nor any way to update the UI with a status bar with progress of server side processing.

**Comment by majohannsen** [comment]
Having a similar problem...

When I select files after clicking on the dropzone they get uploaded on submit. But when I drag and drop files they just get ignored on submit.

**Comment by Entropiks** [comment]
I am not able to reproduce this issue. 

The selected to upload data is returned through using the 'handleChange' prop. From there you can do whatever you want with the data (exactly the same as a standard html input field).

**Comment by KarimMokhtar** [comment]
> I am not able to reproduce this issue.
> 
> The selected to upload data is returned through using the 'handleChange' prop. From there you can do whatever you want with the data (exactly the same as a standard html input field).

Correct.
