### ISSUE TITLE
Multiple files upload

### ISSUE THREAD

**Issue by alebreiz** [KarimMokhtar/react-drag-drop-files#116]
Is there an example how to implement multiple files upload? Thank you.

**Comment by KarimMokhtar** [comment]
> The `multiple` prop seems not to work 100% right now.
> 
> If you put the `multiple` prop BUT you select only **one** file, the `handleChange` is triggered with an empty objet, something like follow :
> 
> ```js
> { '0': { } }
> ```
> 
> so, for now, I will not use this feature right now if I was you ;)
> 
> EDIT: i made some update to the codebox to give you more insights https://codesandbox.io/p/sandbox/react-drag-drop-files-forked-jlc23n

@optyler  your sandbox showing the file uploaded correctly. please check again.
![Screenshot 2024-10-22 at 23 44 03](https://github.com/user-attachments/assets/5523ff78-447f-4f7a-b352-fe224b9125fc)

**Comment by KarimMokhtar** [comment]
> An example request shouldn't be added as an issue. If you see the homepage there is an example on Sandbox with multiple uploads. https://codesandbox.io/s/react-drag-drop-files-sghbp

@alebreiz  You chould check the example in the demo it's using multiple feature

**Comment by optyler** [comment]
Hi @KarimMokhtar, I tried my sandbox and all seems OK now, maybe a peer dep update fixed the issue.
