### ISSUE TITLE
Incorrect use of <label for=FORM_ELEMENT> warning

### ISSUE THREAD

**Issue by Entropiks** [KarimMokhtar/react-drag-drop-files#122]
**Problem**
It seems that the input returned by the `<FileUploader />` does not have a matching id to it's parent label prompting a warning from issues on chrome. Since the input and label are not exposed, this change should be a global fix in the repo. 

![react-drag-drop-bug](https://github.com/KarimMokhtar/react-drag-drop-files/assets/14153504/47c3e0fc-012b-4604-83b9-f6e222008144)

**Error Message ( Chrome Issues Tab )**
Incorrect use of <label for=FORM_ELEMENT>
The label's for attribute doesn't match any element id. This might prevent the browser from correctly autofilling the form and accessibility tools from working correctly.
To fix this issue, make sure the label's for attribute references the correct id of a form field.

**Browser**
Chrome Version 113.0.5672.127 (Official Build) (64-bit)

**Fix**
The label returned from <FileUploader /> should have a for="file" prop that matches the labels input id="file" property.

**Resource**
https://www.w3schools.com/tags/att_label_for.asp
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/for

**Comment by picasocro1** [comment]
I confirm the bug - I tried to write tests using [Testing Library](https://testing-library.com/) and finished with the following error:

> Found a label with the text of: Upload files, however no form control was found associated to that label. Make sure you're using the "for" attribute or "aria-labelledby" attribute correctly.

**Comment by KarimMokhtar** [comment]
solved in https://github.com/KarimMokhtar/react-drag-drop-files/pull/131
you can use v. 2.3.11
