### ISSUE TITLE
How to change label text "Uploaded Successfully! Upload another?"

### ISSUE THREAD

**Issue by bwselakkiya** [KarimMokhtar/react-drag-drop-files#127]

**Comment by HaroldBernard** [comment]
+1

**Comment by Muhammadsaqib11** [comment]
useEffect(() => {

  // Find the element with the class "sc-fqkvVR"
  const element = document.querySelector(".sc-fqkvVR");


  if (element) {
    const successSpan = element.querySelector("span");

    const innerSpans = element.querySelectorAll("span");

  console.log("getElementsByClassName",successSpan?.textContent , element);


    if (successSpan && successSpan.textContent.includes("Successfully")) {
      console.log("The word 'Successfully' is present.");

      // Update the text content of the found span
      successSpan.textContent = "please !"; // Replace with your desired text
    } else {
      console.log("The word 'Successfully' is not present.");
    }
    if (element && element.textContent.includes("another")) {
      console.log("The word 'another' is present.");

      // Update the text content of the found span
      element.textContent = " Please Upload Again"; // Replace with your desired text
    } else {
      console.log("The word 'Another' is not present.");
    }
  }
}, [checkFile]);


i have solve this issue  through core JS

**Comment by melforbes** [comment]
The above didn't work for me, here's what did, with an explanation, and also without the console.logs:

**Comment by Stephane-Ag** [comment]
There's now a `uploadedLabel` prop to do this now since 2 weeks ago: https://github.com/KarimMokhtar/react-drag-drop-files/pull/137
In v.2.3.11 and above
