### ISSUE TITLE
No way to change label color?

### ISSUE THREAD

**Issue by SciSaif** [KarimMokhtar/react-drag-drop-files#128]

**Comment by cimslab** [comment]
Have you tried this:
`<FileUploader classes="dragging">`

CSS:
```.dragging{
background-color: red !important;
color: yellow !important;
}```

**Comment by goncalhurtado** [comment]
What I did to solve it was first to check the tags it contains in the inspector and then add the necessary colors through SCSS.
 I've included screenshots below, hope it helps!
<img width="443" alt="Captura de pantalla 2024-03-21 a la(s) 14 06 38" src="https://github.com/KarimMokhtar/react-drag-drop-files/assets/132021861/8d5b09ea-c975-4b4f-9f0d-8ba1af562cb1">
<img width="399" alt="Captura de pantalla 2024-03-21 a la(s) 14 07 24" src="https://github.com/KarimMokhtar/react-drag-drop-files/assets/132021861/896018dd-e27b-4062-93d3-76466108ec30">

**Comment by KarimMokhtar** [comment]
usinig styles with `!important` should solve the issue as mentioned above.
