### ISSUE TITLE
[ Outline ] Outline on file select

### ISSUE THREAD

**Issue by Bishal-think201** [KarimMokhtar/react-drag-drop-files#135]
In Version 2.3.8 there is no issue. 

But in the latest version when a user select a file then we get a black outline.

**Comment by peppapig13132** [comment]
Hi @Bishal-think201 
Recently, I installed v2.3.10 and it looks good.
You can check your global CSS, or add custom class.
`classes` can help you with this.
I resolved responsive issue with this option.
https://github.com/KarimMokhtar/react-drag-drop-files?tab=readme-ov-file#options (classes)
