### ISSUE TITLE
Selecting same file again, not working

### ISSUE THREAD

**Issue by udarts** [KarimMokhtar/react-drag-drop-files#143]
I am using version 2.3.10, but the issue of trying to upload same file multiple times is still not working for me.
The text: Successfully uploaded keeps showing for me, while it should be reset to default.

I have included the fileOrFiles param as it is mentioned in the doc.

**Comment by KarimMokhtar** [comment]
It should be working fine, please check the demo example.

![Screenshot 2024-10-23 at 00 10 32](https://github.com/user-attachments/assets/92fe1ee3-6798-4a58-8197-b097fdc0ba9e)
