### ISSUE TITLE
Error on upload file

### ISSUE THREAD

**Issue by akashi7** [KarimMokhtar/react-drag-drop-files#18]
failed to upload file and there are giving me this error
![error](https://user-images.githubusercontent.com/61908937/138675494-9443c130-12b5-41d7-b65c-d4a4532dd06e.JPG)
r

**Comment by KarimMokhtar** [comment]
Hello @akashi7  
This error is regarding the type or size error of the file.

**Comment by marcbernalencora** [comment]
Hi Karim, I think the problem is related when the file they try to upload has more than one dot on the filename. I am having the issue myself on my tests and also on your demo. Try to upload a file called like this: tests.example.jpg

Regards,

**Comment by KarimMokhtar** [comment]
Hi @marcbernalencora , Thank you so much for your comment. But i tried it with the use case you say and it's working fine.
Could you please tell me the fileTypes you are using and the file name?
![Screenshot from 2022-01-26 20-53-56](https://user-images.githubusercontent.com/25772844/151228088-f43131b5-c6c6-4198-a76a-a16fce622c42.png)
