### ISSUE TITLE
Codesandbox example does not work

### ISSUE THREAD

**Issue by maxxims** [KarimMokhtar/react-drag-drop-files#23]
Your example on https://codesandbox.io/s/react-drag-drop-files-sghbp is not working properly, any file uploaded gives the Type/Size error.

**Comment by KarimMokhtar** [comment]
![Screenshot from 2021-12-29 22-49-46](https://user-images.githubusercontent.com/25772844/147702350-258bc810-1c9c-4a96-85a4-910aca7b20d3.png)
Hello @maxxims 
Thanks for your interest in the library, it's well tested and also I have tried it again right now and it's working well.
So, Please check again and make sure of the size and type of the file you are trying to upload.
