### ISSUE TITLE
handle change is called 2 times after drag and drop

### ISSUE THREAD

**Issue by theone3nu** [KarimMokhtar/react-drag-drop-files#27]
Steps to reproduce.
Drag an image and drop. handleChange getting called twice.

https://codesandbox.io/s/react-drag-drop-files-forked-0z4mm

**Comment by KarimMokhtar** [comment]
@theone3nu Thank you so much for your contribution.
Would you like to solve it and create a PR? btw if you don't have time we gonna solve it in the next push.
Thanks again.

**Comment by theone3nu** [comment]
@KarimMokhtar sure please provide me the access to raise pr.

**Comment by KarimMokhtar** [comment]
@theone3nu You can just fork the repo and make your changes on the "dev" branch and then you will be able to create PR

**Comment by theone3nu** [comment]
Thanks. When will be the next release so that i can remove fix from my frontend code in the current app @KarimMokhtar

**Comment by KarimMokhtar** [comment]
@theone3nu  I have published it as a quick fix on version 2.2.4 please check it

**Comment by Rdeshpande1** [comment]
> Steps to reproduce. Drag an image and drop. handleChange getting called twice.
> 
> https://codesandbox.io/s/react-drag-drop-files-forked-0z4mm


Use onDrop method for drag/drop file upload and onSelect method for file selection
