### ISSUE TITLE
Add multiple files

### ISSUE THREAD

**Issue by crazytweeks** [KarimMokhtar/react-drag-drop-files#31]
Very good package which lacks only one feature, that is multiple file selection.

**Comment by KarimMokhtar** [comment]
Hello @crazytweeks  yes it's on our checklist and gonna be added soon.
We also welcome your collaboration if you would like to.
Thanks for your feedback.

**Comment by truptipenkar03** [comment]
Any idea by when you will be adding multiple files feature ?

**Comment by KarimMokhtar** [comment]
Hello @truptipenkar03, Most likely it's gonna be added before the end of this month. 
Thanks for your contribution.

**Comment by KarimMokhtar** [comment]
@truptipenkar03 @crazytweeks  Hello guys, the feature has been added you can now use it.
Thanks to @iamdipanshusingh
