### ISSUE TITLE
How to style the component?

### ISSUE THREAD

**Issue by meetdheeraj** [KarimMokhtar/react-drag-drop-files#36]
I wish to change the border color and border-radius of the component but was not able to. When I add a new className to `classes`, your class `.iciELI` takes precedence over any class I wish to write to add extra CSS.

**Comment by KarimMokhtar** [comment]
it's not possible as the class is added after the styled component one.
![Screenshot from 2022-02-04 14-50-39](https://user-images.githubusercontent.com/25772844/152532175-ce400696-39fd-4d57-8a52-87fe7a32d43e.png)

**Comment by dzyubadmytro** [comment]
[if two classes are in separate files, import the priority file second](https://stackoverflow.com/a/3671560)
So, probably, the issue is that both library styles and user styles are imported randomly, so styles are applied randomly as well
