### ISSUE TITLE
Multiple attribute doesn't work for me

### ISSUE THREAD

**Issue by Gougerik** [KarimMokhtar/react-drag-drop-files#40]
So I like your module it's simple and easy to work with but now I have decided to try it with multiple files but it doesn't work.
My code looks like this:
`<FileUploader
                        multiple={true}
                        ...`
But it's still not able to upload multiple files. I tried also passing true argument as string but didn't work.
Is this problem on my side or anybody has this issue too? Can you please fix this? Thanx.

**Comment by Gougerik** [comment]
@KarimMokhtar @thebedroomprogrammer

**Comment by KarimMokhtar** [comment]
Hi @Gougerik  , Thanks for your contribution.
Actually, it's working fine. could you please send the version you are using and what's the behavior happening with you?

**Comment by Gougerik** [comment]
> Hi @Gougerik , Thanks for your contribution. Actually, it's working fine. could you please send the version you are using and what's the behavior happening with you?

I'm using the latest version ofc.

**Comment by Gougerik** [comment]
@KarimMokhtar I can add you on discord so I can send you screenshots or we can call if that's needed.

**Comment by KarimMokhtar** [comment]
I think there is no need for discord you can put the screenshots with the comment.
Also here is mine 
![Screenshot from 2022-02-09 00-34-13](https://user-images.githubusercontent.com/25772844/153087043-b8830e42-5739-4d37-897b-bd3b97a91b6d.png)

**Comment by Gougerik** [comment]
> I think there is no need for discord you can put the screenshots with the comment. Also here is mine ![Screenshot from 2022-02-09 00-34-13](https://user-images.githubusercontent.com/25772844/153087043-b8830e42-5739-4d37-897b-bd3b97a91b6d.png)

@KarimMokhtar OK...
![image](https://user-images.githubusercontent.com/41547709/153090579-3a98b26a-a075-4946-b975-c00f4566dfa8.png)

**Comment by KarimMokhtar** [comment]
@Gougerik  Please confirm, Are you using v.2.3.2 or a lower one?

**Comment by Gougerik** [comment]
> @Gougerik Please confirm, Are you using v.2.3.2 or a lower one?

@KarimMokhtar yes, 2.3.2

**Comment by KarimMokhtar** [comment]
Ok, Could you please write a sample of the code you use on codesandbox and share it so i could debug?

**Comment by KarimMokhtar** [comment]
Hi, @Gougerik I have some thoughts that may be wrong; Could you please try the traditional approach be remove and install the library again? : "D
Also, i will close this issue and here is my email: karimmokhtar28@gmail.com
Please confirm here if it's working after reinstalling 
if not email me we can arrange a meeting to debug it. I would be more than happy to help.
Thanks for your contribution.
