### ISSUE TITLE
Option to change uploaded text

### ISSUE THREAD

**Issue by syllith** [KarimMokhtar/react-drag-drop-files#53]
Hello, great job with this. Could you please add an option to change the text "Uploaded Successfully!. Upload another?". There are options to change everything else, but not this it seems.

**Comment by KarimMokhtar** [comment]
@syllith Actually it's too customized so you could use the option of passing a "children" with the design you would like.
we may add this feature in the future but if you would like to contribute by adding it we gonna be very happy. Thanks.
