### ISSUE TITLE
"File type is not supported"

### ISSUE THREAD

**Issue by jitendrapal080791** [KarimMokhtar/react-drag-drop-files#55]
"File type is not supported" when selecting MP3 file

**Comment by KarimMokhtar** [comment]
Hi @jitendrapal080791  Thanks for your contribution.
Could you please provide a screenshot or steps so we can fix it. Also we tested it and it's working fine as you can see here:
![Screenshot from 2022-04-02 14-37-03](https://user-images.githubusercontent.com/25772844/161383679-fa758475-971e-4ad9-b995-e21f5a05d6bc.png)

**Comment by jitendrapal080791** [comment]
Thanks @KarimMokhtar, It is working fine with latest version.
