### ISSUE TITLE
How to preview image upload

### ISSUE THREAD

**Issue by vinhkaito** [KarimMokhtar/react-drag-drop-files#57]
It works great for me but i don't know how to get the preview image, can you help me ? thanks you so much

**Comment by KarimMokhtar** [comment]
Hello, @vinhkaito Actually we have left the Preview up to you so you could use any design you would like.
Thanks for your contribution.

**Comment by gith-amitm7** [comment]
I tried a similar implementation using custom file item renderers, but clicking on them results into the built in label to open the file picker rather than doing something else like previewing. Tried preventing propagation, still didn't work.
