### ISSUE TITLE
Upload File window opens twice & disabled doesn't work in Next.js

### ISSUE THREAD

**Issue by room9design** [KarimMokhtar/react-drag-drop-files#61]
When the package is imported and run in Next.js, the file upload window opens twice when the component is clicked. Also, the file upload is still clickable & will open a window even when disabled is set to true. I haven't been able to replicate this in regular React apps.

**Comment by KarimMokhtar** [comment]
@room9design  Thanks for your contribution.
This one is solved now on v.2.3.6
