### ISSUE TITLE
Image re-upload is not working

### ISSUE THREAD

**Issue by kakarlasaiteja** [KarimMokhtar/react-drag-drop-files#63]
When we upload an image, and then try to upload the same image again, change event is not firing. Also is it possible to make it compatible with react 17?

**Comment by Mohamed-Elhawary** [comment]
@kakarlasaiteja I have the same issue here, did you get a proper solution ??

**Comment by SHUJAAT-DEV** [comment]
I am facing the same issue, any solutions?

**Comment by KarimMokhtar** [comment]
duplicate for #59
