### ISSUE TITLE
Upload file window shows twice

### ISSUE THREAD

**Issue by dummy26** [KarimMokhtar/react-drag-drop-files#64]
After selecting a file from the file window the window shows up again.

This seems to be happening when the `FileUploader` is not passed `name`  attribute.

Here's the link for codesandbox - https://codesandbox.io/s/react-drag-drop-files-forked-ctcpi3

**Comment by KarimMokhtar** [comment]
@dummy26  Thanks for your contribution.
this bug was solved on v.2.3.6 you can try it now.
