### ISSUE TITLE
Reset file value

### ISSUE THREAD

**Issue by dar-gol** [KarimMokhtar/react-drag-drop-files#70]
When I upload image, I don't know how I can remove the success view (Uploaded Successfully!)

![image](https://user-images.githubusercontent.com/72765170/173043996-7cc0ed5d-cafe-4cb8-a88d-1c2e9d5cb7ea.png)

**Comment by irawanfirmansyah** [comment]
> When I upload image, I don't know how I can remove the success view (Uploaded Successfully!)
> 
> ![image](https://user-images.githubusercontent.com/72765170/173043996-7cc0ed5d-cafe-4cb8-a88d-1c2e9d5cb7ea.png)

You can customize the component by wrapping your custom component with `FileUploader`. Something like this:

`<FileUploader>
    . . . custom component goes here
</FileUploader>
`

**Comment by dar-gol** [comment]
Okay, yes this works :) Thanks for answer 👍
