### ISSUE TITLE
Adding aria tags

### ISSUE THREAD

**Issue by hepiyellow** [KarimMokhtar/react-drag-drop-files#87]
Hi,

I don't see any way to add `aria` tags to the `<input/>` element.

I need to add tags like:
`aria-required`
`aria-describedby`
`aria-invalid`

Is there a workaround?

Or should I make a PR for it?

**Comment by KarimMokhtar** [comment]
Hi @hepiyellow  unfortunately there is no work around so please create a PR for that.

**Comment by KarimMokhtar** [comment]
solved in v.2.3.11
