### ISSUE TITLE
First two uploaded images take long time

### ISSUE THREAD

**Issue by fasenderos** [KarimMokhtar/react-drag-drop-files#92]
Hi, I noticed the first two images take a long time to upload, about 7/8 seconds each. I've seen the same problem happen in the demo on [codesandbox](https://codesandbox.io/s/react-drag-drop-files-sghbp) as well.
There is something wrong on my side or it's a known bug?
Thansk

**Comment by KarimMokhtar** [comment]
the files should be uploaded immediately. please check the codebase
