### ISSUE TITLE
Feature request: required prop & focus indicator

### ISSUE THREAD

**Issue by KieranGreenwood** [KarimMokhtar/react-drag-drop-files#93]
It would be great if basic `required` validation was added. E.g:

```<FileUploader required={isRequired} />```

- add required as a prop
- apply required prop to input field
- change input css from `display: none` to `display: block`
- add input css `opacity: 0`;
- add input css `position: absolute;`
- add input css `pointer-events: none;`

The CSS changes mean:
- Native browser validation prompts display when required is set to true.
- The dropzone can receive keyboard focus and have a visible focus indicator (for accessibility, see [WCAG 2.4.7](https://www.w3.org/TR/WCAG21/#focus-visible))

**Comment by KarimMokhtar** [comment]
fixed in version 2.3.9
