### ISSUE TITLE
style drag and drop border

### ISSUE THREAD

**Issue by aayalapalacin** [KarimMokhtar/react-drag-drop-files#96]
Hello! Any way to change default border styling? Seems like it's currently border style dotted and color blue. Thanks!

**Comment by KarimMokhtar** [comment]
> ```
> <FileUploader
>   classes="myClass"
>   />
>   
>   then
>   
>   .myClass {
>      border-style: solid;
>   }
> ```

almost correct.
you just need to add `!important` to override the default value:
`border-style: solid !important;`
