### ISSUE TITLE
Can't upload same file multiple times.

### ISSUE THREAD

**Issue by Arsh1a** [KarimMokhtar/react-drag-drop-files#99]
handleChange does not work if we upload same file again.

**Comment by enjoijkee** [comment]
If you mean re-uploading after value resetting, pass your value into `fileOrFiles` property. Helped for me.

`
const [file, setFile] = useState<File>(null)
...
<FileUploader  
  types={ ['mp4', 'mkv'] }
  handleChange={ (file: File) => setFile(file) }
  fileOrFiles={ file } />
`
